### ISSUE TITLE
Is there a way to test the entire process.stdout/stderr output?

### ISSUE THREAD

**Issue by CMCDragonkai** [EpicEric/jest-mock-process#13]
If I call `process.stdout.write` multiple times, this is intended to produce multiple lines.

The composite output is an entire message.

I'd like to be able to write a test to see that the entire output is a particular message, rather than having to match the exact number of times the function is called.

Is there a way to do this?

**Comment by EpicEric** [comment]
You can use the [mock property](https://jestjs.io/docs/mock-functions#mock-property) as usual for that, and join the individual call arguments into a single string:

```js
var mockStdout = mockProcess.mockProcessStdout();
// ... test calls go here ...
var entireOutput = mockStdout.mock.calls.map(call => call[0]).join("");
```

**Comment by CMCDragonkai** [comment]
Thanks.
