### ISSUE TITLE
Mock process.uptime() with custom value

### ISSUE THREAD

**Issue by lwojcik** [EpicEric/jest-mock-process#16]
Hi!

I'm looking for a way to mock `process.uptime()`, preferably with a custom value, and your package seems to be the closest to what I'm looking at. Any chance to add?

If not, are you open for a PR adding this feature?

EDIT: I figured out how to do that in my app, but my PR offer remains open. :)

**Comment by EpicEric** [comment]
Added in version 2.0.0.
