### ISSUE TITLE
Implementation problem

### ISSUE THREAD

**Issue by marvingreenberg** [EpicEric/jest-mock-process#17]
Just reading the documentation, it seems like this is impossible to be correct, however the mock for process.exit is defined.

```
const mockEnvironment = mockRun(() => {
  process.stdout.write("stdout payload");
  process.stderr.write("stderr payload");
  process.exit(-1);
  console.log("log payload");
  return 10;
});
expect(mockEnvironment.result).toEqual(10);
```

`process.exit(any value)` will always exit.   From the node docs,

```
The process.exit() method instructs Node.js to terminate the process synchronously with an exit status of code
```

As a result the `console.log` and `return` should never be called, and mockEnvironment.result should be undefined.   The `process.exit` implementation should always be implemented as a thrown error that gets handled by the mock environment or else these tests don't correctly model real behavior.

**Comment by EpicEric** [comment]
You are correct that this behavior does not follow the Node specification, but neither does throwing an error, according to the docs quote you included. Terminating the process causes Jest to hang indefinitely, and the default implementation as a no-op prevents this (although you can also opt into the "throw exception" behavior).
