### ISSUE TITLE
Provide some helpers

### ISSUE THREAD

**Issue by pkoch** [EpicEric/jest-mock-process#3]
I was writing some code with your lib (https://gist.github.com/pkoch/44cd30b618bfd6d92baa3907b26a58f0), and I noticed that I introduced a bunch of glue code that I wish had been provided to me.

I think that this package should offer something like `mockedRun`, and perhaps something like `lineize`. Less sure about the latter.

Thoughts? Open to PRs?

**Comment by EpicEric** [comment]
I think something like `mockedRun` would be a good addition. Not sure about `lineize` -- I'd have users handle the regular `.mock.calls` array with the Jest API they're used to, and then let them implement something like this individually if they feel it's necessary, with whichever extra dependencies they need.

You are free to go ahead and open a PR for the former. One addition I'd make to `mockedRun` is let users pass an optional error to be raised on the mocked `process.exit`, and then return that same value in another property:

https://github.com/EpicEric/jest-mock-process/blob/82460c748fe1d151b30518517fe50b8aec7eb30f/lib/index.ts#L5-L6

**Comment by pkoch** [comment]
Made an initial PR, let's keep the discussion going there.

**Comment by EpicEric** [comment]
`mockedRun` is now available in `jest-mock-process` 1.3.0.
